from .universidad import Universidad
from .carrera import Carrera
from .ciclo import Ciclo
from .universidad_carrera import UniversidadCarrera
from .usuario import Usuario
from .curso import Curso
from .tema import Tema
from .nota import Nota
from .sugerencia import Sugerencia
from .recurso import Recurso